test

diff --git a/.github/workflows/runAsimSchemaAndDataTesters.yaml b/.github/workflows/runAsimSchemaAndDataTesters.yaml
--- a/.github/workflows/runAsimSchemaAndDataTesters.yaml
+++ b/.github/workflows/runAsimSchemaAndDataTesters.yaml
@@ -108,43 +108,43 @@ jobs:
         run: |
               python .script/tests/asimParserTest/VerifyASimParserTemplate.py
   Run-ASim-Parser-Filtering-Tests:
-      name: Run ASim Parser Filtering tests
-      runs-on: ubuntu-latest
-      environment: Staging
-      steps:
-        - name: Checkout pull request branch
-          uses: actions/checkout@v3
-          with:
-            ref: ${{ github.event.pull_request.head.ref }}
-            repository: ${{ github.event.pull_request.head.repo.full_name }}
-            persist-credentials: false
-        - name: Setup git config
-          run: |
-            git config --local user.name "github-actions[bot]"
-            git config --local user.email "<>"
-              fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
-        - name: Merge main into pull request branch
-          run: |
-            git merge origin/main
-            Conflicts=$(git ls-files -u | wc -l)
-            if [ "$Conflicts" -gt 0 ] ; then
-              echo "There is a merge conflict. Aborting"
-              git merge --abort
-              exit 1
-            fi
-        - name: Setup Python
-          uses: actions/setup-python@v2
-          with:
-            python-version: '3.x'
-        - name: Install dependencies
-          run: |
-                python -m pip install --upgrade pip
-        - name: Login to Azure Public Cloud
-          uses: azure/login@v2
-          with:
-            client-id: ${{ secrets.AZURE_CLIENT_ID }}
-            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-            allow-no-subscriptions: true
-        - name: Run Python script
-          run: |
-            python .script/tests/asimParsersTest/ASimFilteringTest.py
+    name: Run ASim Parser Filtering tests
+    runs-on: ubuntu-latest
+    environment: Staging
+    steps:
+      - name: Checkout pull request branch
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          persist-credentials: false
+      - name: Setup git config
+        run: |
+          git config --local user.name "github-actions[bot]"
+          git config --local user.email "<>"
+            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
+      - name: Merge main into pull request branch
+        run: |
+          git merge origin/main
+          Conflicts=$(git ls-files -u | wc -l)
+          if [ "$Conflicts" -gt 0 ] ; then
+            echo "There is a merge conflict. Aborting"
+            git merge --abort
+            exit 1
+          fi
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+      - name: Install dependencies
+        run: |
+              python -m pip install --upgrade pip
+      - name: Login to Azure Public Cloud
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          allow-no-subscriptions: true
+      - name: Run Python script
+        run: |
+          python .script/tests/asimParsersTest/ASimFilteringTest.py
