Update runAsimSchemaAndDataTesters.yaml

diff --git a/.github/workflows/runAsimSchemaAndDataTesters.yaml b/.github/workflows/runAsimSchemaAndDataTesters.yaml
--- a/.github/workflows/runAsimSchemaAndDataTesters.yaml
+++ b/.github/workflows/runAsimSchemaAndDataTesters.yaml
@@ -25,7 +25,8 @@ permissions:
   contents: read
   
 jobs: 
-  run-asim-testers:
+  Run-ASim-Schema-Data-tests:
+    name: Run ASim Schema and Data testers
     runs-on: ubuntu-latest
     environment: Staging
     steps:
@@ -50,7 +51,7 @@ jobs:
           git config --local user.name "github-actions[bot]"
           git config --local user.email "<>"
 
-      - name: Merge master into pull request branch
+      - name: Merge main into pull request branch
         run: |
           git merge origin/main
           Conflicts=$(git ls-files -u | wc -l)
@@ -68,3 +69,41 @@ jobs:
           azPSVersion: "latest"
           errorActionPreference: continue
           failOnStandardError: false
+  Run-ASim-TemplateValidation:
+    name: Run ASim Template Validation tests
+    runs-on: ubuntu-latest
+    environment: Staging
+    steps:
+      - name: Checkout pull request branch
+        uses: actions/checkout@v3
+        with:
+            ref: ${{github.event.pull_request.head.ref}}
+            repository: ${{github.event.pull_request.head.repo.full_name}}
+            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
+            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
+      - name: Setup git config
+        run: |
+              git config --local user.name "github-actions[bot]"
+              git config --local user.email "<>"
+      - name: Merge main into pull request branch
+        run: |
+              git merge origin/main
+              Conflicts=$(git ls-files -u | wc -l)
+              if [ "$Conflicts" -gt 0 ] ; then
+                echo "There is a merge conflict. Aborting"
+                git merge --abort
+                exit 1
+              fi
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+      - name: Install dependencies
+        run: |
+              python -m pip install --upgrade pip
+              pip install requests
+              pip install PyYAML
+              pip install tabulate
+      - name: Run Python script
+        run: |
+              python .script/tests/asimParserTest/VerifyASimParserTemplate.py
